### ISSUE TITLE
Throw system-error or condition when file not found?

### ISSUE THREAD

**Issue by rekado** [mwette/guile-libyaml#4]
Evaluating `(read-yaml-file "/this/does/not/exist")` we get this uncaught error:

```
guile: api.c:313: yaml_parser_set_input_file: Assertion `file' failed.
Aborted
```

Would it be possible to catch errors and rethrow them as Guile exceptions?

**Comment by mwette** [comment]
Rekado, Do you mean something like ``(make-exception-with-message (string-append "file not found: " filename)``

**Comment by mwette** [comment]
Working this with scm-error and newer exceptions ...

**Comment by mwette** [comment]
updated in commit 2bdacb72a65ab63264b2edc9dac9692df7ec9b3e
